services:
  server:
    build:
      context: .
    environment:
      OGAME_AUTO_INSTALL: ${OGAME_AUTO_INSTALL:-1}
      OGAME_MDB_HOST: ${OGAME_MDB_HOST:-mysql}
      OGAME_MDB_USER: ${OGAME_MDB_USER:-root}
      OGAME_MDB_PASS: ${OGAME_MDB_PASS:-${MYSQL_ROOT_PASSWORD:-123}}
      OGAME_MDB_NAME: ${OGAME_MDB_NAME:-master}
      OGAME_UNI_AUTO_INSTALL: ${OGAME_UNI_AUTO_INSTALL:-${OGAME_AUTO_INSTALL:-1}}
      OGAME_UNI_URL: ${OGAME_UNI_URL:-localhost:8888}
      OGAME_STARTPAGE: ${OGAME_STARTPAGE:-http://localhost:8888}
      OGAME_UNI_DB_HOST: ${OGAME_UNI_DB_HOST:-mysql}
      OGAME_UNI_DB_USER: ${OGAME_UNI_DB_USER:-root}
      OGAME_UNI_DB_PASS: ${OGAME_UNI_DB_PASS:-${MYSQL_ROOT_PASSWORD:-123}}
      OGAME_UNI_DB_NAME: ${OGAME_UNI_DB_NAME:-uni}
      OGAME_UNI_DB_PREFIX: ${OGAME_UNI_DB_PREFIX:-uni1_}
      OGAME_UNI_DB_SECRET: ${OGAME_UNI_DB_SECRET:-docker-secret}
      OGAME_UNI_MDB_ENABLE: ${OGAME_UNI_MDB_ENABLE:-1}
      OGAME_UNI_LANG: ${OGAME_UNI_LANG:-en}
      OGAME_UNI_NUM: ${OGAME_UNI_NUM:-1}
      OGAME_UNI_SPEED: ${OGAME_UNI_SPEED:-1}
      OGAME_UNI_FLEET_SPEED: ${OGAME_UNI_FLEET_SPEED:-1}
      OGAME_UNI_GALAXIES: ${OGAME_UNI_GALAXIES:-9}
      OGAME_UNI_SYSTEMS: ${OGAME_UNI_SYSTEMS:-499}
      OGAME_UNI_MAX_USERS: ${OGAME_UNI_MAX_USERS:-12500}
      OGAME_UNI_START_DM: ${OGAME_UNI_START_DM:-0}
      OGAME_UNI_ACS: ${OGAME_UNI_ACS:-4}
      OGAME_UNI_FID: ${OGAME_UNI_FID:-30}
      OGAME_UNI_DID: ${OGAME_UNI_DID:-0}
      OGAME_UNI_RAPID: ${OGAME_UNI_RAPID:-1}
      OGAME_UNI_MOONS: ${OGAME_UNI_MOONS:-1}
      OGAME_UNI_BATTLE_ENGINE: ${OGAME_UNI_BATTLE_ENGINE:-../cgi-bin/battle}
      OGAME_UNI_PHP_BATTLE: ${OGAME_UNI_PHP_BATTLE:-1}
      OGAME_UNI_BATTLE_MAX: ${OGAME_UNI_BATTLE_MAX:-1000000}
      OGAME_UNI_FORCE_LANG: ${OGAME_UNI_FORCE_LANG:-0}
      OGAME_UNI_MAX_WERF: ${OGAME_UNI_MAX_WERF:-999}
      OGAME_UNI_FEED_AGE: ${OGAME_UNI_FEED_AGE:-60}
      OGAME_EXT_BOARD: ${OGAME_EXT_BOARD:-}
      OGAME_EXT_DISCORD: ${OGAME_EXT_DISCORD:-}
      OGAME_EXT_TUTORIAL: ${OGAME_EXT_TUTORIAL:-}
      OGAME_EXT_RULES: ${OGAME_EXT_RULES:-}
      OGAME_EXT_IMPRESSUM: ${OGAME_EXT_IMPRESSUM:-}
      OGAME_ADMIN_EMAIL: ${OGAME_ADMIN_EMAIL:-admin@example.local}
      OGAME_ADMIN_PASSWORD: ${OGAME_ADMIN_PASSWORD:-admin}
    ports:
      - "8888:80"
    volumes:
      - web_configs:/var/www/html/persistent_configs
    depends_on:
      - mysql
      - mailhog # Add dependency on mailhog

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-123}
      MYSQL_DATABASE: ${OGAME_MDB_NAME:-master}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mailhog:
    image: mailhog/mailhog
    ports:
      # This is the web UI where you will view the emails
      - "8026:8025"
      # This is the SMTP port PHP will connect to
      # - "1025:1025"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 100M
    ports:
      - "8080:80"
    depends_on:
      - mysql
    restart: unless-stopped

volumes:
  mysql_data:
  web_configs:
