services:
  goapp:
    build:
      context: .
      dockerfile: Dockerfile.golang
    environment:
      OGAME_ENV: ${OGAME_ENV:-development}
      OGAME_HTTP_ADDR: :8080
      OGAME_LEGACY_BASE_URL: ${OGAME_LEGACY_BASE_URL:-http://localhost:8888}
      OGAME_PUBLIC_UNIVERSES: ${OGAME_PUBLIC_UNIVERSES:-}
      OGAME_MASTER_DB_ENABLE: ${OGAME_MASTER_DB_ENABLE:-1}
      OGAME_MDB_HOST: ${OGAME_MDB_HOST:-mysql}
      OGAME_MDB_USER: ${OGAME_MDB_USER:-root}
      OGAME_MDB_PASS: ${OGAME_MDB_PASS:-${MYSQL_ROOT_PASSWORD:-123}}
      OGAME_MDB_NAME: ${OGAME_MDB_NAME:-master}
      OGAME_UNI_DB_ENABLE: ${OGAME_UNI_DB_ENABLE:-1}
      OGAME_UNI_DB_HOST: ${OGAME_UNI_DB_HOST:-mysql}
      OGAME_UNI_DB_USER: ${OGAME_UNI_DB_USER:-root}
      OGAME_UNI_DB_PASS: ${OGAME_UNI_DB_PASS:-${MYSQL_ROOT_PASSWORD:-123}}
      OGAME_UNI_DB_NAME: ${OGAME_UNI_DB_NAME:-uni}
      OGAME_UNI_DB_PREFIX: ${OGAME_UNI_DB_PREFIX:-uni1_}
      OGAME_UNI_DB_SECRET: ${OGAME_UNI_DB_SECRET:-docker-secret}
    ports:
      - "${OGAME_GO_PORT:-8890}:8080"
