import { existsSync } from "node:fs";
import { writeFile } from "node:fs/promises";
import { resolve } from "node:path";

type BrowserName = "chromium" | "firefox";

type NavReport = {
  generatedAt: string;
  browserName: BrowserName;
  legacyBaseURL: string;
  migratedBaseURL: string;
  loginUser?: string;
  seedOptions?: { includeAdminSeeds?: boolean };
  thresholds: { maxDiffRatio: number };
  allPass: boolean;
  summary: {
    screens: number;
    edges: number;
    matchedEdges: number;
    targetScreens: number;
    exactDiffPass: number;
    exactDiffFail: number;
  };
  discoveries: { edges: { pass: boolean }[] }[];
  targetResults: { key: string; pass: boolean; diff?: { diffRatio: number; changedPixels: number; totalPixels: number } }[];
};

const rootDir = resolve(import.meta.dir, "../..");
const browsers: BrowserName[] = ["chromium", "firefox"];
const reports = (
  await Promise.all(
    browsers.map(async (browser) => {
      const path = resolve(rootDir, ".tmp/playwright-navigation-visual", browser, "report.json");
      if (!existsSync(path)) {
        return null;
      }
      return JSON.parse(await Bun.file(path).text()) as NavReport;
    })
  )
).filter((report): report is NavReport => report !== null);

if (reports.length === 0) {
  throw new Error("no navigation visual reports found");
}

const gapKeys = Array.from(
  new Set(reports.flatMap((report) => report.targetResults.filter((target) => !target.pass).map((target) => target.key)))
).sort();
const generatedAt = new Date().toISOString();
const latest = reports[reports.length - 1];
const loginUsers = Array.from(new Set(reports.map((report) => report.loginUser ?? "unknown"))).sort();
const adminSeedStates = Array.from(new Set(reports.map((report) => (report.seedOptions?.includeAdminSeeds ? "included" : "excluded")))).sort();
const matchedEdges = reports.reduce((sum, report) => sum + report.summary.matchedEdges, 0);
const totalEdges = reports.reduce((sum, report) => sum + report.summary.edges, 0);
const exactFailures = reports.reduce((sum, report) => sum + report.summary.exactDiffFail, 0);
const lines = [
  "# Navigation Visual Coverage",
  "",
  "Generated by `testing/e2e/run-playwright-navigation-visual-e2e.sh`. Keep this file under 4KB; full edge lists, JSON, and screenshots live under `.tmp/playwright-navigation-visual/`.",
  "",
  "## Scope",
  "",
  "- Seeds: public legacy aliases plus authenticated game, optional admin, alliance, statistics, messages, notes, report, phalanx, and fleet-template screens.",
  "- Edges: internal GET anchors, `document.location` handlers, popup/open handlers, hover tooltip hrefs, select option URLs, and GET forms.",
  "- Mutating POST flows remain covered by their flow-specific E2E scripts.",
  "",
  "## Latest Strict Run",
  "",
  `- Generated: ${generatedAt}`,
  `- Legacy: ${latest.legacyBaseURL}`,
  `- Migrated: ${latest.migratedBaseURL}`,
  `- Login User: ${loginUsers.join(", ")}`,
  `- Admin Seeds: ${adminSeedStates.join(", ")}`,
  `- Exact diff threshold: ${formatRatio(latest.thresholds.maxDiffRatio)}`,
  "",
  "| Browser | Screens | Edges | Matched | Targets | Exact Pass | Exact Fail | Result |",
  "| --- | ---: | ---: | ---: | ---: | ---: | ---: | --- |",
  ...reports.map((report) =>
    `| ${report.browserName} | ${report.summary.screens} | ${report.summary.edges} | ${report.summary.matchedEdges} | ${report.summary.targetScreens} | ${report.summary.exactDiffPass} | ${report.summary.exactDiffFail} | ${report.allPass ? "PASS" : "FAIL"} |`
  ),
  "",
  "## Current Exact-Diff Gaps",
  "",
  "| Target | Chromium | Firefox |",
  "| --- | ---: | ---: |",
  ...(gapKeys.length === 0
    ? ["| None | 0 | 0 |"]
    : gapKeys.map((key) => `| \`${key}\` | ${gapCell(reports.find((report) => report.browserName === "chromium"), key)} | ${gapCell(reports.find((report) => report.browserName === "firefox"), key)} |`)),
  "",
  "## Status Notes",
  "",
  "- Route discovery is complete for the current seed set: both browsers matched every discovered edge.",
  `- This pass matched ${matchedEdges}/${totalEdges} discovered edges and syncs Docker DB-backup fixtures before comparison.`,
  exactFailures === 0 ? "- Both browser rows report `Exact Fail` as 0." : `- Remaining exact-diff failures: ${exactFailures}.`,
  adminSeedStates.length === 1 && adminSeedStates[0] === "excluded" ? "- Admin-only screens were excluded; run again with admin seeds before claiming admin-tool visual parity." : "- Admin seed coverage is included in this report."
];

await writeFile(resolve(rootDir, "testing/e2e/COVERAGE-navigation-visual.md"), `${lines.join("\n")}\n`);

function gapCell(report: NavReport | undefined, key: string): string {
  const target = report?.targetResults.find((candidate) => candidate.key === key);
  if (!target) {
    return "-";
  }
  if (target.pass || !target.diff) {
    return "0";
  }
  return `${formatRatio(target.diff.diffRatio)} (${target.diff.changedPixels}px)`;
}

function formatRatio(value: number): string {
  if (value === 0) {
    return "0";
  }
  return `${(value * 100).toFixed(3)}%`;
}
