package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

var descriptionPattern = regexp.MustCompile(`(?s)\$LOCA\["en"\]\["LONG_(\d+)"\]\s*=\s*"((?:\\.|[^"\\])*)";`)

func main() {
	input := flag.String("input", "", "legacy techlong.php path")
	output := flag.String("output", "", "generated Go output path")
	flag.Parse()
	if *input == "" || *output == "" {
		panic("input and output are required")
	}

	source, err := os.ReadFile(*input)
	if err != nil {
		panic(err)
	}
	descriptions := map[int]string{}
	for _, match := range descriptionPattern.FindAllSubmatch(source, -1) {
		id, err := strconv.Atoi(string(match[1]))
		if err != nil {
			panic(err)
		}
		descriptions[id] = strings.ReplaceAll(string(match[2]), `\"`, `"`)
	}
	if len(descriptions) == 0 {
		panic("no legacy technology descriptions found")
	}

	ids := make([]int, 0, len(descriptions))
	for id := range descriptions {
		ids = append(ids, id)
	}
	sort.Ints(ids)

	var generated bytes.Buffer
	generated.WriteString("// Code generated by cmd/gentechlong; DO NOT EDIT.\n\n")
	generated.WriteString("package game\n\n")
	generated.WriteString("var legacyTechnologyLongDescriptions = map[int]string{\n")
	for _, id := range ids {
		fmt.Fprintf(&generated, "\t%d: %q,\n", id, descriptions[id])
	}
	generated.WriteString("}\n")
	if err := os.WriteFile(*output, generated.Bytes(), 0o644); err != nil {
		panic(err)
	}
}
